In [9]:
from gplearn.genetic import SymbolicRegressor
from symbolic_regression import get_equations
import numpy as np
import torch as t

In [10]:
def function(X):
    return (X[:, 0]**2 + 4 * X[:, 1] + 4).unsqueeze(-1)

In [4]:
X = t.rand((100, 2))
print(X[:3])
y = function(X)
print(y[:3])

tensor([[0.0485, 0.7103],
        [0.3329, 0.2843],
        [0.1369, 0.9737]])
tensor([[6.8437],
        [5.2482],
        [7.9135]])


In [5]:
sr = SymbolicRegressor(
    population_size=5000,
    generations=40, stopping_criteria=0.001,
    p_crossover=0.7, p_subtree_mutation=0.1,
    p_hoist_mutation=0.05, p_point_mutation=0.1,
    max_samples=0.9, verbose=1,
    parsimony_coefficient=0.01, random_state=0
)
sr.fit(X, y.squeeze(dim=-1))

    |   Population Average    |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0    38.13          23588.6        7          1.11315         0.889813      3.61m
   1    19.26          9.73101       59         0.396989         0.591577      2.64m
   2    23.44          11.8322       11         0.302933         0.285764      2.62m
   3    19.03          6.12308       25         0.147765          0.19919      2.50m
   4    18.52          4.95059       25         0.144579         0.227867      2.41m
   5    18.05          4.53769       19         0.109481        0.0950109      2.43m
   6    16.09          5.06936       25        0.0683383        0.0987907      2.23m
   7    16.03          4.88351       25        0.0715555        0.0698358      2.31m
   8    16.17           4.5423       25        0.0696828        0.0866901  

SymbolicRegressor(generations=40, max_samples=0.9, p_crossover=0.7,
                  p_hoist_mutation=0.05, p_point_mutation=0.1,
                  p_subtree_mutation=0.1, parsimony_coefficient=0.01,
                  population_size=5000, random_state=0, stopping_criteria=0.001,
                  verbose=1)

In [12]:
print(sr)

add(add(0.790, X0), mul(div(mul(-0.277, -0.797), sub(0.696, 0.645)), add(0.670, X1)))


In [13]:
sr._program.execute(t.tensor([[2, 2]]))

tensor([14.2701], dtype=torch.float64)

In [27]:
print(srs[0])

add(div(0.581, 0.176), add(add(add(add(X1, X1), X1), add(0.543, X1)), sub(0.581, mul(-0.830, div(div(add(-0.442, mul(X0, X0)), div(0.578, 0.614)), div(0.578, 0.614))))))


In [28]:
srs[0]._program.execute(np.array([[0, 1], [0, 2], [1, 1]]))

array([ 8.00518886, 12.00518886,  8.94136859])

In [14]:
x0 = np.arange(-1, 1, 1/10.)
x1 = np.arange(-1, 1, 1/10.)
x0, x1 = np.meshgrid(x0, x1)
y_truth = x0**2 - x1**2 + x1 - 1


In [15]:
X_train = t.rand(100, 2).detach().numpy()
y_train = X_train[:, 0]**2 - X_train[:, 1]**2 + X_train[:, 1] - 1

In [16]:
est_gp = SymbolicRegressor(population_size=5000,
                           generations=20, stopping_criteria=0.01,
                           p_crossover=0.7, p_subtree_mutation=0.1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=0.01, random_state=0)
est_gp.fit(X_train, y_train)


    |   Population Average    |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0    38.13          2669.81       11        0.0654363        0.0748386      1.73m
   1     9.47           1.9699       11        0.0663953        0.0662079      1.10m
   2     6.38          2.10702       11        0.0635211        0.0920751     57.15s
   3     4.91           1.0223       11        0.0621707         0.104229     52.24s
   4     3.40          0.63074        9        0.0682394        0.0656751     46.97s
   5     3.48         0.667487        3         0.071136         0.140014     45.29s
   6     3.32          1.12612        3        0.0698823         0.151297     41.47s
   7     3.42         0.724485        3        0.0716385         0.135492     37.27s
   8     3.35         0.676246        3        0.0705049         0.145694  

SymbolicRegressor(max_samples=0.9, p_crossover=0.7, p_hoist_mutation=0.05,
                  p_point_mutation=0.1, p_subtree_mutation=0.1,
                  parsimony_coefficient=0.01, population_size=5000,
                  random_state=0, stopping_criteria=0.01, verbose=1)

In [18]:
print(est_gp._program)

sub(X0, 0.985)


In [113]:
est_gp = SymbolicRegressor(population_size=5000,
                           generations=20, stopping_criteria=0.001,
                           p_crossover=0.7, p_subtree_mutation=0.1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=0.01, random_state=0)

x2 = t.rand((500, 3)).detach().numpy()
print(x2[:3])
y2 = x2[:,0] ** 2 + x2[:,1] * 2
print(y2[:3])

[[0.7056529  0.2468515  0.3755384 ]
 [0.7790533  0.5010682  0.15524495]
 [0.42188656 0.7039841  0.0691489 ]]
[0.99164903 1.6090603  1.5859565 ]


In [114]:
est_gp.fit(x2, y2)

    |   Population Average    |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0    33.42      7.39237e+06        9        0.0845733        0.0833497      1.66m
   1     8.55          1.96871        9        0.0835435        0.0926175      1.05m
   2     6.20          1.28072        7                0                0     55.93s


SymbolicRegressor(max_samples=0.9, p_crossover=0.7, p_hoist_mutation=0.05,
                  p_point_mutation=0.1, p_subtree_mutation=0.1,
                  parsimony_coefficient=0.01, population_size=5000,
                  random_state=0, stopping_criteria=0.001, verbose=1)

In [115]:
print(est_gp)

add(mul(X0, X0), add(X1, X1))


In [108]:
est_gp._program.execute(np.array([[5, 1]]))

array([27])